config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Custom sign out route
  devise_scope :user do
    delete 'users/sign_out', to: 'devise/sessions#destroy'
  end

  # ActiveAdmin routes for admin_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Root route
  root 'home#index'

  # Static pages routes
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # Products routes
  resources :products, only: [:index, :show] do
    collection do
      get 'new_arrivals'
      get 'recently_updated'
    end
  end

  # Categories routes
  resources :categories, only: [:index, :show]

  # Cart routes
  resource :cart, only: [:show] do
    collection do
      post 'add_item'
      delete 'remove_item/:id', to: 'carts#remove_item', as: 'remove_item'
      patch 'update_quantity', to: 'carts#update_quantity', as: 'update_quantity'
      get 'checkout', as: 'checkout'
    end
  end

  # Orders routes
  resources :orders, only: [:index, :show]

  # Checkout routes
  resources :checkout, only: [:new, :create, :show] do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  # Addresses routes
  resources :addresses, only: [:new, :create]

  # Admin namespace for static_pages
  namespace :admin do
    resources :static_pages, only: [:index, :edit, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province

  validates :line1, presence: true
  validates :city, presence: true
  # validates :zipcode, presence: true, numericality: { only_integer: true }

  def self.ransackable_attributes(auth_object = nil)
    ["city", "country", "created_at", "id", "line1", "line2", "province_id", "state", "street",
     "updated_at", "user_id", "zipcode"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }

  # Define which attributes can be searched by Ransack
  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

# Since ApplicationRecord is an abstract class and typically does not contain attributes, there are no validations needed directly in this class.

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :province
  belongs_to :address
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items

  before_save :update_total

  validates :status, presence: true
  validates :total_amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def subtotal
    order_items.sum { |item| item.quantity * item.price }
  end

  def gst
    subtotal * (province.gst || 0) / 100
  end

  def pst
    subtotal * (province.pst || 0) / 100
  end

  def hst
    subtotal * (province.hst || 0) / 100
  end

  def qst
    subtotal * (province.qst || 0) / 100
  end

  def total_taxes
    gst + pst + hst + qst
  end

  def total_amount
    subtotal + total_taxes
  end

  private

  def update_total
    self.total_amount = subtotal + total_taxes
  end
end

app/models/order_item.rb
# app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  after_create :notify_discord

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "description", "price", "category_id", "image_url", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end

  private

  def notify_discord
    DiscordNotificationService.new.notify_new_product(self)
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
  has_many :orders

  validates :name, presence: true
  validates :gst, :pst, :hst, :qst,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "gst", "pst", "hst", "qst", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["addresses", "orders"]
  end
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, presence: true
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :address, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, class_name: 'CartItem', dependent: :destroy

  accepts_nested_attributes_for :address

 # validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10) # Paginate products
    @categories = Category.all # Ensure @categories is set
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tax_helper.rb
module TaxHelper
  def calculate_taxes(cart_items, province)
    subtotal = cart_items.sum { |item| item["quantity"].to_i * item["price"].to_f }
    gst = subtotal * (province.gst / 100.0)
    pst = subtotal * (province.pst / 100.0)
    hst = subtotal * (province.hst / 100.0)
    qst = subtotal * (province.qst / 100.0)
    total_taxes = gst + pst + hst + qst
    total_amount = subtotal + total_taxes
    {
      subtotal:     subtotal.round(2),
      gst:          gst.round(2),
      pst:          pst.round(2),
      hst:          hst.round(2),
      qst:          qst.round(2),
      total_taxes:  total_taxes.round(2),
      total_amount: total_amount.round(2)
    }
  end
end

app/views/categories/index.html.erb
<div class="mt-4">
  <%= form_tag(new_arrivals_products_path, method: :get, class: "flex items-center") do %>
    <%= select_tag(:filter, options_for_select([["Select filter", ""], ["New Arrivals", "new_arrivals"], ["Recently Updated", "recently_updated"]]), class: "form-select mr-2") %>
    <%= submit_tag "Apply", class: "btn btn-primary" %>
  <% end %>
</div>

<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->
<%= render 'shared/breadcrumbs', category: @category %>

<div class="mt-4">
  <%= form_tag(new_arrivals_products_path, method: :get, class: "flex items-center") do %>
    <%= select_tag(:filter, options_for_select([["Select filter", ""], ["New Arrivals", "new_arrivals"], ["Recently Updated", "recently_updated"]]), class: "form-select mr-2") %>
    <%= submit_tag "Apply", class: "btn btn-primary" %>
  <% end %>
</div>

<h1 class="mt-6 text-xl font-semibold">Explore by Category</h1>
<ul class="flex space-x-4 mt-4">
  <% @categories.uniq.each do |category| %>
    <li><%= link_to category.name, category_path(category), class: "text-blue-500 hover:text-blue-700" %></li>
  <% end %>
</ul>

<h1><u></u><%= @category.name %> Products</u></h1>
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
  <% @products.each do |product| %>
    <div class="border border-gray-200 p-4 rounded-md shadow-md">
      <% if product.image_url.present? %>
        <%= link_to image_tag(product.image_url, class: "w-full h-auto rounded-md mb-2"), product_path(product) %>
      <% else %>
        <div class="w-full h-auto rounded-md mb-2 bg-gray-200 flex items-center justify-center" style="height: 300px;">
          <span class="text-gray-600">No image found</span>
        </div>
      <% end %>
      <h2 class="text-lg font-semibold"><%= product.name %></h2>
      <p class="text-gray-600"><%= product.description %></p>
      <p class="mt-2 font-bold text-gray-800"><%= number_to_currency(product.price) %></p>
      <p class="mt-2 text-sm text-gray-500">Category: <%= @category.name %></p>
    </div>
  <% end %>
</div>
<%= paginate @products %>